# Generated by Django 2.0.7 on 2018-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_beds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
